package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class Basket {

	// id is generated by the database and set on the object automagically
	int id;
	String name;
	float conversionAmount;
	boolean active;
	Date dateCreated;

	Basket() {
		// needed by ormlite
	}

	/**
	 * Creates a new basket
	 * 
	 * @param n
	 *            Name of the basket
	 * @param ca
	 *            Conversion Amount
	 * @param a
	 *            Whether active or not
	 */
	public Basket(String n, float ca, boolean a) {
		this.name = n;
		this.conversionAmount = ca;
		this.active = a;
		this.dateCreated = new Date();
	}

	public static JSONArray getListToJSONArray(List<Basket> basketList)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (Basket b : basketList) {
			ja.put(b.toJSONObject());
		}

		return ja;
	}

	public JSONObject toJSONObject() throws JSONException {
		JSONObject basketJsonObject = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		basketJsonObject.put("id", this.getId());
		basketJsonObject.put("name", this.getName());
		basketJsonObject.put("conversion_amount", this.getConversionAmount());
		basketJsonObject.put("active", this.isActive());
		basketJsonObject.put("date_created",
				dateFormatter.format(this.getDateCreated()));

		return basketJsonObject;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("name=").append(name);
		sb.append(", ").append("conversionAmount=").append(conversionAmount);
		sb.append(", ").append("active=").append(active);
		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("dateCreated=")
				.append(dateFormatter.format(dateCreated));
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public float getConversionAmount() {
		return conversionAmount;
	}

	public boolean isActive() {
		return active;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

}
