package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class Customer {

	// id is generated by the database and set on the object automagically
	int id;
	String mobileNumber;
	String customerFirstName;
	String customerLastName;
	String customerMiddleName;
	String customerAddress;
	String customerRegion;
	 
	String customerCity;
	String customerPicture;
	String customerBirthDate;
	Date dateCreated;
	int totalSukiPoints;

	Customer() {
		// needed by ormlite
	}

	public Customer(String mn) {
		this.mobileNumber = mn;
		this.dateCreated = new Date();
		this.totalSukiPoints = 0;
		this.customerFirstName = "";
		this.customerMiddleName = "";
		this.customerMiddleName = "";
		this.customerPicture = "";
		this.customerAddress = "";
		this.customerBirthDate = "";
	}

	public static JSONArray getListToJSONArray(List<Customer> l)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (Customer o : l) {
			ja.put(o.toJSONObject());
		}

		return ja;
	}

	public JSONObject toJSONObject() throws JSONException {
		JSONObject jo = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		jo.put("id", this.getId());
		jo.put("mobile_number", this.getMobileNumber());
		jo.put("total_suki_points", this.getTotalSukiPoints());
		jo.put("date_created", dateFormatter.format(this.getDateCreated()));

		return jo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("mobileNumber=").append(mobileNumber);
		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=")
				.append(dateFormatter.format(dateCreated));
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public String getMobileNumber() {
		return mobileNumber;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public int getTotalSukiPoints() {
		return totalSukiPoints;
	}

	public void setTotalSukiPoints(int totalSukiPoints) {
		this.totalSukiPoints = totalSukiPoints;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getCustomerFirstName() {
		return customerFirstName;
	}

	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	public String getCustomerLastName() {
		return customerLastName;
	}

	public void setCustomerLastName(String customerLastName) {
		this.customerLastName = customerLastName;
	}

	public String getCustomerMiddleName() {
		return customerMiddleName;
	}

	public void setCustomerMiddleName(String customerMiddleName) {
		this.customerMiddleName = customerMiddleName;
	}

	public String getCustomerPicture() {
		return customerPicture;
	}

	public void setCustomerPicture(String customerPicture) {
		this.customerPicture = customerPicture;
	}

	public String getCustomerBirthDate() {
		return customerBirthDate;
	}

	public void setCustomerBirthDate(String birthDayText) {
		this.customerBirthDate = birthDayText;
	}

	public String getCustomerAddress() {
		return customerAddress;
	}

	public String getCustomerRegion() {
		return customerRegion;
	}

	public void setCustomerRegion(String customerRegion) {
		this.customerRegion = customerRegion;
	}

	public String getCustomerCity() {
		return customerCity;
	}

	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

}
