package com.hatchpointsolutions.sssrewards.app.objects;

import java.util.Date;


public class DeviceKey {

    // id is generated by the database and set on the object automagically
    int id;
    String key;
    Date dateCreated;

    DeviceKey() {

    }

    public DeviceKey(String k) {
        this.key = k;
        this.dateCreated = new Date();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

}
