package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class Item {

	// id is generated by the database and set on the object automagically
	int id;
	Basket basket;
	String name;
	float srp;
	boolean active;
	Date dateCreated;

	Item() {
		// needed by ormlite
	}

	/**
	 * Creates the item object
	 * 
	 * @param b
	 *            The basket of this item
	 * @param n
	 *            Name of this item
	 * @param s
	 *            Suggested retail price
	 * @param a
	 *            Active or not
	 */
	public Item(Basket b, String n, float s, boolean a) {
		this.basket = b;
		this.name = n;
		this.srp = s;
		this.active = a;
		this.dateCreated = new Date();
	}

	public static JSONArray getListToJSONArray(List<Item> l)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (Item o : l) {
			ja.put(o.toJSONObject());
		}

		return ja;
	}

	public JSONObject toJSONObject() throws JSONException {
		JSONObject jo = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		jo.put("id", this.getId());
		jo.put("basket_id", this.getBasket().getId());
		jo.put("name", this.getName());
		jo.put("srp", this.getSrp());
		jo.put("is_active", this.isActive());
		jo.put("date_created", dateFormatter.format(this.getDateCreated()));

		return jo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("name=").append(name);
		sb.append(", ").append("srp=").append(srp);
		sb.append(", ").append("active=").append(active);
		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=")
				.append(dateFormatter.format(dateCreated));
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Basket getBasket() {
		return basket;
	}

	public void setBasket(Basket basket) {
		this.basket = basket;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getSrp() {
		return srp;
	}

	public void setSrp(float srp) {
		this.srp = srp;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
