package com.hatchpointsolutions.sssrewards.app.objects;


public class Password {

	// id is generated by the database and set on the object automagically
	private int id;
	private String password;

	Password() {
		// needed by ormlite
	}

	public Password(String password) {
		this.password = password;
		// try {
		// MessageDigest md = MessageDigest.getInstance("MD5");
		// byte[] passwordMd5 = md.digest(p.getBytes("UTF-8"));
		// p = passwordMd5.toString();
		// this.password = p;
		// } catch (NoSuchAlgorithmException e) {
		// // TODO Auto-generated catch block
		// e.printStackTrace();
		// } catch (UnsupportedEncodingException e) {
		// // TODO Auto-generated catch block
		// e.printStackTrace();
		// }
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
