package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class Purchase {

	// id is generated by the database and set on the object automagically
	int id;
	Customer customer;
	int totalPoints;
	float receiptAmount;
	Date datePurchased;
	Date dateCreated;

	Purchase() {
		// needed by ormlite
	}

	/**
	 * Creates a Purchase object
	 * 
	 * @param c
	 *            The customer who made the purchase
	 * @param tp
	 *            Total points of this purchase
	 * @param ra
	 *            The amount of this receipt
	 * @param dp
	 *            Date of the purchase
	 */
	public Purchase(Customer c, int tp, float ra, Date dp) {
		this.customer = c;
		this.totalPoints = tp;
		this.receiptAmount = ra;
		this.datePurchased = dp;
		this.dateCreated = new Date();
	}

	public static JSONArray getListToJSONArray(List<Purchase> l)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (Purchase o : l) {
			ja.put(o.toJSONObject());
		}

		return ja;
	}

	public JSONObject toJSONObject() throws JSONException {
		JSONObject jo = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		jo.put("id", this.getId());
		jo.put("customer_id", this.getCustomer().getId());
		jo.put("total_points", this.getTotalPoints());
		jo.put("receipt_amount", this.getReceiptAmount());
		jo.put("date_purchased", dateFormatter.format(this.getDatePurchased()));
		jo.put("date_created", dateFormatter.format(this.getDateCreated()));

		return jo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("customer=").append(customer.toString());
		sb.append(", ").append("totalPoints=").append(totalPoints);
		sb.append(", ").append("receiptAmount=").append(receiptAmount);
		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("datePurchased=")
				.append(dateFormatter.format(datePurchased));
		sb.append(", ").append("dateCreated=")
				.append(dateFormatter.format(dateCreated));
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public int getTotalPoints() {
		return totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public float getReceiptAmount() {
		return receiptAmount;
	}

	public void setReceiptAmount(float receiptAmount) {
		this.receiptAmount = receiptAmount;
	}

	public Date getDatePurchased() {
		return datePurchased;
	}

	public void setDatePurchased(Date datePurchased) {
		this.datePurchased = datePurchased;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
