package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class RedemptionTransaction {

	// id is generated by the database and set on the object automagically
	int id;
	Redemption redemption;
	Customer customer;
	int totalPoints;
	int quantity;
	Date dateCreated;

	RedemptionTransaction() {
		// needed by ormlite
	}

	public RedemptionTransaction(Redemption r, Customer c, int tp, int qty) {
		this.redemption = r;
		this.customer = c;
		this.totalPoints = tp;
		this.quantity = qty;
		this.dateCreated = new Date();
	}

	public static JSONArray getListToJSONArray(List<RedemptionTransaction> l)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (RedemptionTransaction o : l) {
			ja.put(o.toJSONObject());
		}

		return ja;
	}

	@SuppressLint("SimpleDateFormat")
	public JSONObject toJSONObject() throws JSONException {
		JSONObject jo = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		jo.put("id", this.getId());
		jo.put("redemption_id", this.getRedemption().getId());
		jo.put("customer_id", this.getCustomer().getId());
		jo.put("total_points", this.getTotalPoints());
		jo.put("quantity", this.getQuantity());
		jo.put("date_created", dateFormatter.format(this.getDateCreated()));

		return jo;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Redemption getRedemption() {
		return redemption;
	}

	public void setRedemption(Redemption redemption) {
		this.redemption = redemption;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public int getTotalPoints() {
		return totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
