package com.hatchpointsolutions.sssrewards.app.objects;

import android.annotation.SuppressLint;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@SuppressLint("SimpleDateFormat")
public class Redemption {

	// id is generated by the database and set on the object automagically
	int id;
	String name;
	int points;
	boolean active;
	Date dateCreated;

	Redemption() {
		// needed by ormlite
	}

	public Redemption(String n, int p, boolean t) {
		this.name = n;
		this.points = p;
		this.active = t;
		this.dateCreated = new Date();
	}

	public static JSONArray getListToJSONArray(List<Redemption> l)
			throws JSONException {
		JSONArray ja = new JSONArray();

		for (Redemption o : l) {
			ja.put(o.toJSONObject());
		}

		return ja;
	}

	public JSONObject toJSONObject() throws JSONException {
		JSONObject jo = new JSONObject();

		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss");
		jo.put("id", this.getId());
		jo.put("name", this.getName());
		jo.put("points", this.getPoints());
		jo.put("date_created", dateFormatter.format(this.getDateCreated()));

		return jo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("name=").append(name);
		sb.append(", ").append("points=").append(points);
		sb.append(", ").append("active=").append(active);
		SimpleDateFormat dateFormatter = new SimpleDateFormat(
				"MM/dd/yyyy HH:mm:ss.S");
		sb.append(", ").append("date=")
				.append(dateFormatter.format(dateCreated));
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPoints() {
		return points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
